name: Scrape Cattle Text Metrics

on:
  schedule:
    - cron: '30 10 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: List files to verify structure
        run: |
          echo "=== Root directory ==="
          ls -la
          echo ""
          echo "=== Script directory ==="
          ls -la script/
          echo ""
          echo "=== Current directory ==="
          pwd
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install puppeteer
        
      - name: Run scraper (try from root)
        run: node ./script/scrape_text_metrics.js
        
      - name: Show any errors
        if: failure()
        run: |
          echo "Script failed. Trying to read the file:"
          cat ./script/scrape_text_metrics.js | head -20
          
      - name: Commit updated metrics
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "Update cattle text metrics [automated]"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
